In [1]:
import pandas as pd
import numpy as np

In [7]:
df=pd.read_csv('titanic1.csv')

In [8]:
df.head()

Unnamed: 0  Survived  Age  SibSp  Parch     Fare  male  Q  S  Pclass_2  \
0           0         0   22      1      0   7.2500     1  0  1         0   
1           1         1   38      1      0  71.2833     0  0  0         0   
2           2         1   26      0      0   7.9250     0  0  1         0   
3           3         1   35      1      0  53.1000     0  0  1         0   
4           4         0   35      0      0   8.0500     1  0  1         0   

   Pclass_3  
0         1  
1         0  
2         1  
3         0  
4         1

In [9]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [10]:
df.head()

Survived  Age  SibSp  Parch     Fare  male  Q  S  Pclass_2  Pclass_3
0         0   22      1      0   7.2500     1  0  1         0         1
1         1   38      1      0  71.2833     0  0  0         0         0
2         1   26      0      0   7.9250     0  0  1         0         1
3         1   35      1      0  53.1000     0  0  1         0         0
4         0   35      0      0   8.0500     1  0  1         0         1

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

### Splitting data into train and test

In [12]:
X=df.drop('Survived',axis=1)
y=df['Survived']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0,stratify=y)
X_train.shape,X_test.shape

((711, 9), (178, 9))

### Scaling data

In [13]:
scaler=StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

## Evaluating Models

### Logistic Regression

In [15]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(random_state=0)
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
y_pred=model.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix
confusion=confusion_matrix(y_test,y_pred)
print(confusion)

[[97 13]
 [16 52]]


In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.86      0.88      0.87       110
           1       0.80      0.76      0.78        68

    accuracy                           0.84       178
   macro avg       0.83      0.82      0.83       178
weighted avg       0.84      0.84      0.84       178



In [19]:
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score,roc_auc_score
accuracy=accuracy_score(y_test,y_pred)
f1=f1_score(y_test,y_pred)
precision=precision_score(y_test,y_pred)
recall=recall_score(y_test,y_pred)
roc_auc=roc_auc_score(y_test,y_pred)
print('Accuracy:' ,round(accuracy*100,2))
print('F1:' ,round(f1*100,2))
print('Precision:' ,round(precision*100,2))
print('Recall:' ,round(recall*100,2))
print('ROC_AUC:' ,round(roc_auc*100,2))

Accuracy: 83.71
F1: 78.2
Precision: 80.0
Recall: 76.47
ROC_AUC: 82.33


### KNN

In [20]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=25)
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=25, p=2,
                     weights='uniform')

In [23]:
pred_knn = knn.predict(X_test)
print("CONFUSION MATRIX")
print(confusion_matrix(y_test, pred_knn))
print("CLASSIFICATION REPORT")
print(classification_report(y_test, pred_knn))
accuracy=accuracy_score(y_test,pred_knn)
f1=f1_score(y_test,pred_knn)
precision=precision_score(y_test,pred_knn)
recall=recall_score(y_test,pred_knn)
roc_auc=roc_auc_score(y_test,pred_knn)
print("METRICS")
print('Accuracy:' ,round(accuracy*100,2))
print('F1:' ,round(f1*100,2))
print('Precision:' ,round(precision*100,2))
print('Recall:' ,round(recall*100,2))
print('ROC_AUC:' ,round(roc_auc*100,2))


CONFUSION MATRIX
[[105   5]
 [ 19  49]]
CLASSIFICATION REPORT
              precision    recall  f1-score   support

           0       0.85      0.95      0.90       110
           1       0.91      0.72      0.80        68

    accuracy                           0.87       178
   macro avg       0.88      0.84      0.85       178
weighted avg       0.87      0.87      0.86       178

METRICS
Accuracy: 86.52
F1: 80.33
Precision: 90.74
Recall: 72.06
ROC_AUC: 83.76


### Decision Tree

In [24]:
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier()
clf=clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)

In [26]:
print("CONFUSION MATRIX")
print(confusion_matrix(y_test, y_pred))
print("CLASSIFICATION REPORT")
print(classification_report(y_test, y_pred))
accuracy=accuracy_score(y_test,y_pred)
f1=f1_score(y_test,y_pred)
precision=precision_score(y_test,y_pred)
recall=recall_score(y_test,y_pred)
roc_auc=roc_auc_score(y_test,y_pred)
print("METRICS")
print('Accuracy:' ,round(accuracy*100,2))
print('F1:' ,round(f1*100,2))
print('Precision:' ,round(precision*100,2))
print('Recall:' ,round(recall*100,2))
print('ROC_AUC:' ,round(roc_auc*100,2))

CONFUSION MATRIX
[[85 25]
 [16 52]]
CLASSIFICATION REPORT
              precision    recall  f1-score   support

           0       0.84      0.77      0.81       110
           1       0.68      0.76      0.72        68

    accuracy                           0.77       178
   macro avg       0.76      0.77      0.76       178
weighted avg       0.78      0.77      0.77       178

METRICS
Accuracy: 76.97
F1: 71.72
Precision: 67.53
Recall: 76.47
ROC_AUC: 76.87


### Random Forest

In [40]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 10, n_jobs= 2, random_state=0,max_depth=6, max_features=7)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=6, max_features=7,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [41]:
y_pred=clf.predict(X_test)

In [42]:
print("CONFUSION MATRIX")
print(confusion_matrix(y_test, y_pred))
print("CLASSIFICATION REPORT")
print(classification_report(y_test, y_pred))
accuracy=accuracy_score(y_test,y_pred)
f1=f1_score(y_test,y_pred)
precision=precision_score(y_test,y_pred)
recall=recall_score(y_test,y_pred)
roc_auc=roc_auc_score(y_test,y_pred)
print("METRICS")
print('Accuracy:' ,round(accuracy*100,2))
print('F1:' ,round(f1*100,2))
print('Precision:' ,round(precision*100,2))
print('Recall:' ,round(recall*100,2))
print('ROC_AUC:' ,round(roc_auc*100,2))

CONFUSION MATRIX
[[105   5]
 [ 18  50]]
CLASSIFICATION REPORT
              precision    recall  f1-score   support

           0       0.85      0.95      0.90       110
           1       0.91      0.74      0.81        68

    accuracy                           0.87       178
   macro avg       0.88      0.84      0.86       178
weighted avg       0.87      0.87      0.87       178

METRICS
Accuracy: 87.08
F1: 81.3
Precision: 90.91
Recall: 73.53
ROC_AUC: 84.49


## CONCLUSION 

In [43]:
print('Logistic Regression model: 83.71%')
print('KNN model: 86.52%')
print('Decision Tree: 76.97%')
print('Random Forest model : 87.08%')

Logistic Regression model: 83.71%
KNN model: 86.52%
Decision Tree: 76.97%
Random Forest model : 87.08%


### Random Forest gives the highest accuracy of 87.08%